import fs from "node:fs"
import path from "node:path"
import { pathToFileURL } from "node:url"
import { scan } from "./scan.mjs"
import { windowMap } from "./windows.mjs"
import { ROOT, GENERATED, json, hash, slug, chunks, write, walk, sourceLink, escape, compact } from "./lib.mjs"

const heading = (title) => `# ${title}\n\nGenerated by \`npm run ai:map\`. [code] Static source evidence; conditional/dynamic execution is not runtime verification.\n\n`
const list = (records, doc, description = item => item.expression || item.code || item.text || item.name || "") => records.map(item => `- ${sourceLink(item, doc)} — ${escape(description(item))}`).join("\n") || "No static evidence found."
export function generate(model = scan()) {
    model.windows = windowMap(model)
    const outputs = new Map(), tables = {}
    const put = (file, value) => outputs.set(`${GENERATED}/${file}`, value)
    for (const [table, records] of Object.entries(model).filter(([,value]) => Array.isArray(value))) {
        tables[table] = []
        const groups = ["files", "stores", "channels", "windows", "components"].includes(table) ? records.map(record => [record]) : chunks(records, 25)
        for (let index = 0; index < groups.length; index++) {
            const record = groups[index][0]
            const key = groups[index].length === 1 ? slug(record.id || record.file || record.name || `${index+1}`) : String(index+1).padStart(3,"0")
            const file = `${table}/${key}.json`
            const packed = groups[index].map((record, row) => {
                const copy = { ...record }, parts = {}
                for (const [field, value] of Object.entries(copy)) if (Array.isArray(value) && value.length > 50) {
                    parts[field] = chunks(value, 40).map((piece, part) => {
                        const partFile = `${table}/parts/${key}-${row}-${field}-${part + 1}.json`
                        put(partFile, json(piece)); return partFile
                    })
                    delete copy[field]
                }
                if (Object.keys(parts).length) copy.$parts = parts
                return copy
            })
            put(file, json(packed)); tables[table].push(file)
        }
    }
    const totals = Object.fromEntries(Object.entries(tables).map(([key]) => [key, model[key].length]))
    // The manifest itself must also stay bounded, even for >1,000 source files.
    for(const [name,files] of Object.entries(tables))if(files.length>80)tables[name]={$parts:chunks(files,80).map((part,index)=>{
        const file=`indexes/${name}-${index+1}.json`;put(file,json(part));return file
    })}
    const manifest = { schemaVersion: 2, sourceRevision: model.sourceRevision, compiler: model.compiler, totals, tables, sourceFingerprint: hash(json(model.files.map(file => [file.file, file.hash]))), limitations: ["Static imports only; dynamic computed paths remain unresolved.", "Store methods and $ auto-subscriptions are indexed; arbitrary helper/mutable aliases may escape analysis.", "IPC payload types are explicit contracts when available; untyped endpoints keep source expressions.", "Settings property paths with computed keys use *; store reads also index whole settings values.", "Window reachability is an upper bound across conditional branches; preview is embedded.", "Numeric timings are evaluated only for literals and simple constant arithmetic; null means dynamic, not zero."] }
    put("manifest.json", json(manifest))
    const front = `${GENERATED}/README.md`
    put("README.md", heading("Generated maps") + Object.entries(totals).map(([key,count]) => `- [${key}: ${count}](${key}/README.md)`).join("\n") + "\n\n" + manifest.limitations.map(line => `- ${line}`).join("\n") + "\n")
    function pages(table, entries, render) {
        const links=[]
        for (const entry of entries) {
            const key=slug(entry.id || entry.file || entry.name), doc=`${GENERATED}/${table}/${key}.md`
            const content = render(entry,doc), lines = content.split("\n")
            if (lines.length <= 200) put(`${table}/${key}.md`, content)
            else {
                const pages = chunks(lines, 180).map((part,index) => {
                    const name = `${key}-${index+1}.md`
                    put(`${table}/${name}`, heading(`${entry.id || entry.file || entry.name} (part ${index+1})`) + part.join("\n") + "\n")
                    return `- [Part ${index+1}](${name})`
                })
                put(`${table}/${key}.md`, heading(entry.id || entry.file || entry.name) + pages.join("\n") + "\n")
            }
            links.push(`- [${entry.id || entry.file || entry.name}](${key}.md)`)
        }
        if(links.length<=80)put(`${table}/README.md`,heading(table)+links.join("\n")+"\n")
        else {
            const indexes=chunks(links,80).map((part,index)=>{
                const file=`index-${index+1}.md`;put(`${table}/${file}`,heading(`${table} index ${index+1}`)+part.join("\n")+"\n");return `- [Entries ${index*80+1}–${index*80+part.length}](${file})`
            })
            put(`${table}/README.md`,heading(table)+indexes.join("\n")+"\n")
        }
    }
    pages("stores",model.stores,(store,doc)=>heading(store.id)+`Definition: ${sourceLink(store,doc)}; ${store.factory}; type \`${escape(store.type)}\`.\n\nSaved: ${store.persistence.length ? "yes, with the listed transformations" : "no direct save-object evidence (not proof of transient-only lifetime)"}.\n\n## Reads\n\n${list(store.reads,doc)}\n\n## Writes\n\n${list(store.writes,doc)}\n\n## Transport\n\n${list(store.transports,doc,item=>`${item.role} ${item.channel}/${item.keys.join(",")} — ${item.relation}`)}\n\n## Persistence\n\n${list(store.persistence,doc,item=>`${item.group}/${item.key}${item.transformed ? " (transformed)" : ""}`)}\n`)
    pages("channels",model.channels,(channel,doc)=>{
        const links = model.messages.filter(item=>item.channel===channel.name).map(message=>{
            const name = `${slug(message.id)}.md`, messageDoc = `${GENERATED}/messages/${name}`
            put(`messages/${name}`, heading(message.id)+`## Payload contracts\n\n${list(message.payloads,messageDoc,item=>`${item.contract}: ${item.type}`)}\n\n## Senders\n\n${list(message.senders,messageDoc,item=>`${item.direction}; ${item.payload || "untyped"}`)}\n\n## Handlers\n\n${list(message.handlers,messageDoc,item=>`${item.direction}; ${item.expression}`)}\n`)
            return `- [${message.key}](../messages/${name})`
        })
        return heading(channel.name)+`[JSON endpoints](${slug(channel.name)}.json).\n\n## Message keys\n\n${links.join("\n")}\n\n## Transport endpoints (including dynamic envelopes)\n\n${list(channel.endpoints,doc,item=>`${item.role}: ${item.keys.join(",") || "dynamic message key"}`)}\n`
    })
    pages("windows",model.windows,(window,doc)=>heading(window.id)+`Kind: ${window.kind}. Entry: [${window.entry}](${path.relative(path.dirname(doc),window.entry)}).\n\n${window.note}\n\n${window.limits}\n\n## Received stores\n\n${window.receivedStores.map(id=>`- [${id}](../stores/${slug(id)}.md)`).join("\n") || "No direct receive-store evidence."}\n\n## Received messages\n\n${list(window.receives,doc,item=>`${item.channel}/${item.keys.join(",") || "dynamic"}`)}\n\nUsed stores and reachable files are in [JSON](${slug(window.id)}.json).\n`)
    pages("files",model.files,(file,doc)=>heading(file.file)+`## Imports\n\n${list(file.imports,doc,item=>`${item.kind}: ${item.specifier} → ${item.target || "external/unresolved"}${item.typeOnly ? " (types only)" : ""}`)}\n\n## Imported by\n\n${list(model.files.flatMap(parent=>parent.imports.filter(item=>item.target===file.file)),doc)}\n\n## Components rendered\n\n${list(file.components,doc,item=>`${item.name} → ${item.target || "dynamic"}; props: ${item.props.map(prop=>prop.value).join("; ")}`)}\n\n## Stores used\n\n${[...new Set(file.stores.map(item=>item.store))].map(id=>`- [${id}](../stores/${slug(id)}.md)`).join("\n") || "None detected."}\n\n## Timing\n\n${list(file.timers,doc,item=>`${item.id}: ${item.kind} = ${item.valueMs ?? "dynamic"} ms (${item.expression}); ${item.nearbyComments.join(" ")}`)}\n\n## Workarounds\n\n${list(file.workarounds,doc,item=>`${item.id}: ${item.text}`)}\n`)
    pages("components",model.components,(component,doc)=>heading(component.file)+`## Declared props\n\n${list(component.props,doc)}\n\n## Rendered components and props\n\n${list(component.renders,doc,item=>`${item.name} → ${item.target || "dynamic"}; ${item.props.map(prop=>prop.value).join("; ")}`)}\n`)
    pages("settings",model.settings,(setting,doc)=>heading(setting.id)+`Store: ${setting.store || "none identified"}.\n\n## Definitions\n\n${list(setting.definitions,doc,item=>item.value)}\n\n## Reads\n\n${list(setting.reads,doc)}\n\n## Writes\n\n${list(setting.writes,doc)}\n`)
    for (const table of ["messages","timers","workarounds","diagnostics"]) {
        const links=[]
        chunks(model[table],40).forEach((records,index)=>{
            const key=String(index+1).padStart(3,"0"),doc=`${GENERATED}/${table}/${key}.md`
            const body=records.map(item=>`## ${escape(item.id || item.message)}\n\n`+(item.file ? `${sourceLink(item,doc)}\n\n` : "")+ (table === "settings" ? `Store: ${item.store || "none identified"}.\n\n${list(item.definitions,doc,item=>`default: ${item.value}`)}\n\n${list(item.reads,doc)}\n` : table === "messages" ? `- [Details](${slug(item.id)}.md)\n` : `${escape(item.expression || item.text || item.message)}; ${item.valueMs ?? "dynamic"} ms.\n\n${(item.nearbyComments || []).map(escape).join(" ")}\n`)).join("\n")
            put(`${table}/${key}.md`,heading(`${table} ${key}`)+body);links.push(`- [${key}](${key}.md)`)
        })
        put(`${table}/README.md`,heading(table)+links.join("\n")+"\n")
    }
    return { outputs, model, manifest }
}
export function saveGenerated(result) {
    for (const file of walk(GENERATED)) if (!result.outputs.has(file)) fs.unlinkSync(path.resolve(ROOT,file))
    for (const [file,content] of result.outputs) write(file,content)
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
    const start=performance.now(), result=generate(); saveGenerated(result)
    console.log(`Mapped ${JSON.stringify(result.manifest.totals)} in ${((performance.now()-start)/1000).toFixed(2)}s.`)
}
