import path from "node:path"
import { areas } from "./areas.mjs"
import { loadModel, read, readJson, write, json, hash, slug, sourceLink, escape } from "./lib.mjs"
const model=loadModel(),history=readJson("docs/ai/history/index.json"),decisions=history.tables.flatMap(file=>readJson(file)),references=readJson("docs/ai/references.json",[]).filter(ref=>!ref.document.startsWith("docs/ai/subsystems/") && ref.document!=="docs/ai/SUSPECTED_BUGS.md")
export function claimRef(claim,document,registry=references) {
    const source=read(claim.file),lines=source.split(/\r?\n/),index=lines.findIndex(line=>line.includes(claim.needle))
    if(index<0) throw new Error(`Missing curated source anchor ${claim.file}: ${claim.needle}`)
    const symbol=model.files.find(file=>file.file===claim.file)?.symbols.find(symbol=>symbol.line===index+1)?.name
    const reference={document,file:claim.file,line:index+1,excerpt:claim.needle,fileHash:hash(source),...(symbol?{symbol}:{})}
    registry.push(reference)
    return `[${claim.confidence || "code"}] ${claim.text} (${sourceLink(reference,document)})`
}
for(const area of areas) {
    const document=`docs/ai/subsystems/${area.id}.md`,files=model.files.filter(file=>area.scope.some(prefix=>file.file.startsWith(prefix))),storeIds=[...new Set(files.flatMap(file=>file.stores.map(store=>store.store)))].sort(),messages=[...new Set(files.flatMap(file=>file.ipc.flatMap(endpoint=>endpoint.keys.map(key=>`${endpoint.channel}/${key}`))))].sort(),related=decisions.filter(record=>files.some(file=>file.file===record.file)),timers=files.flatMap(file=>file.timers),workarounds=files.flatMap(file=>file.workarounds)
    const dependencies={sourceRevision:model.manifest.sourceRevision,files:files.map(file=>file.file),stores:storeIds,messages,timingIds:timers.map(item=>item.id),workaroundIds:workarounds.map(item=>item.id),decisions:related.map(record=>({id:record.id,document:record.document,file:record.file,line:record.line}))}
    write(`docs/ai/subsystems/${area.id}.dependencies.json`,json(dependencies))
    const evidence=area.claims.map(claim=>claimRef(claim,document)),rules=area.rules.map(claim=>claimRef(claim,document))
    const keyFiles=[...new Set([...area.claims,...area.rules].map(claim=>claim.file))]
    let content=`# ${area.title}\n\n## Purpose\n\n[code] ${area.purpose} Evidence and entry points are below. Architecture context: [AI_README](../../../AI_README.md).\n\n## Entry points and key files\n\n`+keyFiles.map(file=>`- [code] [${file}](../generated/files/${slug(file)}.md) — imports, callers, component props and symbol definitions.`).join("\n")+`\n\n## Data flow and behavior\n\n`+evidence.map((claim,index)=>`${index+1}. ${claim}`).join("\n")+`\n\n## Stores and messages\n\n[code] Static scope: ${files.length} files, ${storeIds.length} referenced stores, ${messages.length} concrete message keys, ${timers.length} timing entries. [Complete dependency index](${area.id}.dependencies.json) includes conditional and test paths. Runtime use can be narrower.\n\n`+storeIds.slice(0,24).map(id=>`- [code] [${id}](../generated/stores/${slug(id)}.md)`).join("\n")+`\n\n[code] Message families: ${[...new Set(messages.map(id=>id.split("/")[0]))].map(channel=>`[${channel}](../generated/channels/${slug(channel)}.md)`).join(", ") || "none concretely indexed in this scope"}. Full message keys are in the dependency JSON and [IPC index](../generated/messages/README.md).\n\n## Rules that must stay true\n\n`+rules.map(claim=>`- ${claim}`).join("\n")+`\n\n## Known issues and verification limits\n\n[code] Indexed comments are author warnings, not proof that a bug still reproduces in this snapshot:\n\n`+workarounds.slice(0,4).map(item=>`- [code] ${sourceLink(item,document)}: ${escape(item.text)}`).join("\n")+`\n\n[guess] Runtime timing, browser/network behavior and native hardware behavior need observation in the target environment. [Suspected bugs](../SUSPECTED_BUGS.md) distinguish new concerns from companion findings.\n\n## History and behavior findings\n\n`+related.filter(record=>record.sourcedWhy || record.category==="fork-feature" || record.category==="hotspot").slice(0,6).map(record=>`- [${record.confidence}] [${record.id}](${path.relative(path.dirname(document),record.document)}): ${escape(record.what)}.`).join("\n")+`\n\n[code] All ${related.length} related decision IDs and locations are included in the dependency JSON. Use \`ai:ask -- why <file>:<line>\` for exact records; generic commit intent is not an item-specific motive.\n\n`+(area.findings.length?`[code] Companion references: ${area.findings.map(id=>`[${id}](https://github.com/ajdebeer1322/FreeShow/blob/a3cdd7f576480f842077c233c79f6f4c3238fd07/HOW_IT_WORKS.md)`).join(", ")}. These refer to a later source snapshot; they are contextual evidence, not runtime verification here.\n`:`[code] No specific F-001–F-019 companion finding directly assigned to this area. See the [documentation roles](../README.md) before borrowing later behavior claims.\n`)
    if(content.split("\n").length>=400) throw new Error(`${document} exceeds line budget`)
    write(document,content)
}
const doc="docs/ai/SUSPECTED_BUGS.md"
const bugs=[
 {id:"S-001",title:"Explicit project occurrence may be overwritten during activation",evidence:[{file:"src/frontend/components/show/Slides.svelte",needle:"...(projectIndex >= 0",text:"The click path explicitly sends the clicked projectIndex."},{file:"src/frontend/components/helpers/output.ts",needle:"data.projectIndex = active.index",text:"setOutput assigns active selection's index when the show IDs match, without first preserving a supplied projectIndex."}],risk:"[guess] With the same show repeated in a project, a clicked occurrence differing from active selection could acquire the wrong project context for dynamic values. Reproduce with two occurrences/layouts and log click data versus stored out.slide.projectIndex. It may be masked when selection updates before activation.",finding:"No matching F-001–F-019 finding; separate from known auto-size/transition issues."},
 {id:"S-002",title:"Active-only output payload updates are suppressed",evidence:[{file:"src/frontend/utils/receivers.ts",needle:"delete a[id].active",text:"The receiver excludes active from its JSON equality signature."},{file:"src/frontend/utils/receivers.ts",needle:"if (previousOutputs === newOutputs) return",text:"An equal content signature returns before restoring/storing the new active value."}],risk:"[guess] Active-only updates leave the renderer store's active field unchanged. This may be intentional because visibility is controlled elsewhere. Test whether any output-renderer consumers rely on active; do not change the guard without tracing window state.",finding:"No matching F-001–F-019 finding."},
 {id:"S-003",title:"Stage buffer destination filter remains disabled",evidence:[{file:"src/frontend/utils/receivers.ts",needle:"WIP only receive the",text:"The comment records that stage-output capture filtering is unfinished."},{file:"src/frontend/utils/receivers.ts",needle:"a[id] = { buffer, size }",text:"Fresh frames are cached by received ID without checking the selected stage source in this handler."}],risk:"[guess] Multiple stage output sources may consume memory/bandwidth for frames a window never renders. The eventual renderer might filter correctly. Measure incoming IDs, cache growth and actual source selection before judging this a rendering bug.",finding:"No matching F-001–F-019 finding; already recorded as a source WIP, not a new proven defect."}
]
write(doc,"# Suspected bugs and investigation targets\n\nNo product fixes were made. The later HOW_IT_WORKS findings were checked first; known auto-size cache/geometry and transition timing findings are referenced by ID in the subsystem guides rather than re-reported.\n\n"+bugs.map(bug=>`## ${bug.id}: ${bug.title}\n\n${bug.evidence.map(evidence=>claimRef(evidence,doc)).join("\n\n")}\n\n${bug.risk}\n\n[code] Companion overlap check: ${bug.finding}\n`).join("\n"))
write("docs/ai/references.json",json(references))
write("docs/ai/subsystems/README.md","# Subsystem guides\n\n[code] Curated claims cite exact source anchors. Dependency JSON captures the full static scope; conditional imports and tests are navigation evidence, not observed execution. Each guide stays below 400 lines.\n\n"+areas.map(area=>`- [${area.title}](${area.id}.md)`).join("\n")+"\n")
console.log(`Wrote ${areas.length} subsystem guides and ${references.length} reviewed source anchors.`)
